### ISSUE TITLE
Compat for Python 2.7, 3.3, 3.4

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator#16]
Code currently runs on 3.3 and 3.4, and will run on 2.7 with minimal changes.

## Tasks

* [x] Setup CI server integration to run tests on multiple runtimes
* [x] Configure test runner to persist coverage reports
* [x] Add compat.py for handling py2/3 stuff
    * I'm avoiding [six](https://pythonhosted.org/six/) and the like if possible, and this should be fine as long as py2.7 is the oldest runtime we support
    * I'm using [this](https://docs.python.org/3/howto/pyporting.html) as my primary reference

**Comment by pwalsh** [comment]
https://github.com/okfn/tabular-validator/commit/97e7016637ede139d37759648f9a7a221ebbdf51
